### ISSUE TITLE
06-complete-redux yields console error

### ISSUE THREAD

**Issue by janvorwerk** [ProNextJS/state-management-tutorial#9]
Awesome tutorial! 🔥 🚀
Thanks! 🙏

When I run the `06-complete-redux` and navigate from product page to product page, I get a warning in the console:
```
Warning: Cannot update a component (`AverageRating`) while rendering a different component (`AverageRating`). To locate the bad setState() call inside `AverageRating`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
```

This is something I've already had a few times in my app and it seems related to the fact that the render is using a `setState()` when this should only be done in an event handler or a `useEffect()`...

**Comment by jherr** [comment]
Unfortunately that's going to be unavoidable if you want to use a state manager with the App Router. If you use a `useEffect` then you will only get the update after the client has loaded, so you are going to have an SSR result that doesn't have the data. This warning is really just trying to avoid the case where you have code that unconditionally sets state on every render, which would create an infinite loop. In this case we set only once.

If you can think of a better way to do it I'm all ears. This is the current best usage pattern that we have for Redux, verified by the Redux folks themselves.

**Comment by jherr** [comment]
It would be great if it could handle it in strict mode, my guess is that it would be tough because the implementation there is specifically; given a new instance are you leaking from useEffect. Which they can't even detect automatically. You actually have to do the detection yourself. They are just providing the stressor. In this case we really do want to set the state given a fresh instance.

I can't fault them for creating the warning. 99.9% of the time the warning is truly an indication of a problem. It's just that, in this case, it's really the only time that I know of, where you can initialize the store with data that you get from props so that they data is available at SSR time given that `useEffect` doesn't run on the server.

There is a `useMemo` trick I should try out... 🤔 It's something they do at FB to prevent a double render after a prop change if internal state is dependent on the prop state...

FWIW, I hate those warnings too. I alway look to run warning free. In this case I might even preference not using a state manager at all. Which honestly seems to be the preference of the NextJS/React team.

**Comment by janvorwerk** [comment]
Thanks for your feedback!

Interrestingly, the "Zustand" version (which you prounounce very well BTW 😉) is more decoupled and does not generate such a warning. That would be sufficient for me not to consider Redux and favor of Zustand or Jotai (which I already use in React Native).

Whether or not we should use a state manager is yet another question. I started w/o but I am now struggling with an edition that I do in a popover... when I re-open the popover, the edition is not to be seen... unless I refresh the page in between. 

That's how I landed on your very nice tuto ! 👍
